[project]
license = "Apache-2.0"
org-name = "chanakal"
version = "0.5.6"
authors = ["Chanaka Lakmal"]
repository = "https://github.com/ldclakmal/module-instagram"
keywords = ["instagram", "social-network", "photos", "videos"]